/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material 3 style design tokens ported from the Stitch mockups (DESIGN.md)
        "secondary-fixed-dim": "#51df8e",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        outline: "#737685",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#003ea6",
        "on-secondary-fixed": "#00210e",
        "surface-tint": "#2156ca",
        "secondary-container": "#70fda7",
        "surface-container-low": "#f0f3ff",
        "primary-container": "#0047bb",
        "primary-fixed-dim": "#b3c5ff",
        "inverse-on-surface": "#ecf0ff",
        "inverse-surface": "#273143",
        surface: "#f9f9ff",
        primary: "#00328a",
        "on-tertiary-fixed-variant": "#6b3b00",
        "surface-container": "#e8eeff",
        "outline-variant": "#c3c6d6",
        "on-surface-variant": "#434653",
        "on-background": "#111c2d",
        "tertiary-container": "#794300",
        "on-primary-container": "#afc1ff",
        "tertiary-fixed-dim": "#ffb875",
        "on-secondary-container": "#007440",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00174a",
        secondary: "#006d3c",
        "surface-container-highest": "#d9e3fb",
        "on-tertiary-container": "#ffb36b",
        "surface-container-high": "#dfe8ff",
        background: "#f9f9ff",
        "on-surface": "#111c2d",
        "tertiary-fixed": "#ffdcc0",
        "on-tertiary-fixed": "#2d1600",
        "surface-variant": "#d9e3fb",
        "secondary-fixed": "#70fda7",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        tertiary: "#583000",
        "inverse-primary": "#b3c5ff",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#d0daf2",
        "on-secondary-fixed-variant": "#00522c",
        // Unified semantic status colors (NowGo Score bands) — used across
        // map markers, score bars and badges. Consolidated from the two
        // slightly different palettes across the Stitch mockups.
        "semantic-safe": "#007440",
        "semantic-caution": "#ffb36b",
        "semantic-danger": "#ba1a1a",
        // Pulse dashboard chart palette
        "chart-1": "#4F46E5",
        "chart-2": "#10B981",
        "chart-3": "#F59E0B",
        "chart-4": "#EF4444",
        "chart-5": "#8B5CF6",
        "chart-6": "#E5E7EB",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap": "12px",
        "section-gap": "40px",
        gutter: "16px",
        "card-padding": "20px",
        "container-margin": "24px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "score-display": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "score-display": ["36px", { lineHeight: "44px", fontWeight: "800" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
