"""add position to place_list_items

Revision ID: 372a17185dbf
Revises: c1cfe51e9a39
Create Date: 2026-08-20 10:40:37.631322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372a17185dbf'
down_revision: Union[str, Sequence[str], None] = 'c1cfe51e9a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행이 있을 수 있어 서버 기본값 0으로 채운 뒤(added_at 순서를 그대로 유지해도
    # 무방 — 재정렬 전까지는 추가한 순서 = 표시 순서), 이후 삽입은 모델의 파이썬 기본값을 쓴다.
    op.add_column('place_list_items', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # 기존 행은 전부 0으로 깔렸으니, added_at 순서를 그대로 초기 순서로 백필한다.
    op.execute("""
        UPDATE place_list_items pli
        SET position = ranked.rn
        FROM (
            SELECT list_id, contentid,
                   ROW_NUMBER() OVER (PARTITION BY list_id ORDER BY added_at) - 1 AS rn
            FROM place_list_items
        ) ranked
        WHERE pli.list_id = ranked.list_id AND pli.contentid = ranked.contentid
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_list_items', 'position')
    # ### end Alembic commands ###
