"""add place_lists and place_list_items

Revision ID: c1cfe51e9a39
Revises: 42f855dfc306
Create Date: 2026-08-20 09:58:53.206364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cfe51e9a39'
down_revision: Union[str, Sequence[str], None] = '42f855dfc306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('contentid', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contentid'], ['tour_spot.contentid'], ),
    sa.ForeignKeyConstraint(['list_id'], ['place_lists.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'contentid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_list_items')
    op.drop_table('place_lists')
    # ### end Alembic commands ###
